services:
  db_reon:
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8081:8081
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
    depends_on:
      - db_reon
    restart: always
